### PR TITLE
TR-2126 Document maximum days in the future for scheduled transmissions

### PR DESCRIPTION
**Pull request by dremsberg-msys**

### CODE REVIEW

**Comment by dremsberg-msys** [comment]
Matt pointed out there is a statement in this doc that says start_time is  "**Not available in SparkPost EU.** <br />Format: `YYYY-MM-DDTHH:MM:SS+-HH:MM`".   Is that really true?  Or can that be removed.  Seems the feature is enabled as scheduled send?

**Comment by rdawemsys** [comment]
@dremsberg-msys @mtgray-sp This doc change won't ship until 10th February, right? At that point, all of SparkPost will be running on scheduled send.

Given that, we need to remove that note. https://github.com/SparkPost/developers.sparkpost.com/blob/master/content/api/transmissions.apib#L57

**Comment by rdawemsys** [comment]
We also have a time restriction around changing templates used by a scheduled transmission. From https://github.com/SparkPost/developers.sparkpost.com/blob/master/content/api/recipient-lists.apib#L389 :

> Also, if the transmission is scheduled and is within 10 minutes of the scheduled time, the list won't be updatable.

We could in theory reduce that time period once all MTAs are on scheduled send, since the recipient list for transmissions is pulled before generation starts for scheduled send transmissions.

What do you think?

**Comment by mtgray-sp** [comment]
@rdawemsys Can we remove mention of that restriction altogether?

**Comment by rdawemsys** [comment]
@mtgray-sp wrote:

> @rdawemsys Can we remove mention of that restriction altogether?

The one about not being able to update recipient lists less than 10 minutes before a scheduled transmission?

I think we should consider that, but we may want to give ourselves some kind of window, in case Recipient Lists v2 has some kind of restrictions. I can't think _what_ those restrictions would be, but I don't think we should paint ourselves into a corner now.

Part of the reason there is this restriction is because of the way recipient lists and message generation are integrated. There's no separation between them. They are linked at the database level (Cassandra schema).

Perhaps we should capture this question somewhere else. E.g.: in a spike ticket for Recipient Lists V2?

**Comment by dremsberg-msys** [comment]
> @dremsberg-msys @mtgray-sp This doc change won't ship until 10th February, right? At that point, all of SparkPost will be running on scheduled send.
> 
> Given that, we need to remove that note. https://github.com/SparkPost/developers.sparkpost.com/blob/master/content/api/transmissions.apib#L57

I can change the wording to "Delay sending of messages" instead of "Delay generation" ?

**Comment by dremsberg-msys** [comment]
> We also have a time restriction around changing templates used by a scheduled transmission. From https://github.com/SparkPost/developers.sparkpost.com/blob/master/content/api/recipient-lists.apib#L389 :
> 
> > Also, if the transmission is scheduled and is within 10 minutes of the scheduled time, the list won't be updatable.
> 
> We could in theory reduce that time period once all MTAs are on scheduled send, since the recipient list for transmissions is pulled before generation starts for scheduled send transmissions.
> 
> What do you think?
I didn't update the doc around the update window blackout period for things - since that window or configuration hasn't changed.  Do you think it will?   Seems me need to maintain that update restriction.   My thoughts were we would still have that restriction and left the documentation as is in respect to that.

**Comment by dremsberg-msys** [comment]
> Matt pointed out there is a statement in this doc that says start_time is "**Not available in SparkPost EU.**
> Format: `YYYY-MM-DDTHH:MM:SS+-HH:MM`". Is that really true? Or can that be removed. Seems the feature is enabled as scheduled send?

So - we don't advertise it in the EU and that will still hold true until TR-2147.  So even though it works in EU we don't tell them and won't until SPC is changed to match everywhere else.

**Comment by rdawemsys** [comment]
> > @dremsberg-msys @mtgray-sp This doc change won't ship until 10th February, right? At that point, all of SparkPost will be running on scheduled send.
> > Given that, we need to remove that note. https://github.com/SparkPost/developers.sparkpost.com/blob/master/content/api/transmissions.apib#L57
> 
> I can change the wording to "Delay sending of messages" instead of "Delay generation" ?

@dremsberg-msys , yes,  or perhaps: "The system will not attempt to deliver messages until this datetime".

**Pull request merged**
