### PR TITLE
Batch status with querying and paging

### PR DESCRIPTION
**Pull request by avigoldman**

### CODE REVIEW

**Comment by bizob2828** [comment]
if @gwalls approved this then I'm 👍

**Comment by avigoldman** [comment]
Moved from: https://github.com/SparkPost/sparkpost-api-documentation-DEV/pull/352

**Comment by avigoldman** [comment]
I'm gonna hold off on merging this until we know how we want to document the two different batch status endpoints, relative to each other. It seems like the new one can do everything and more that the old one does.

**Comment by nicklemmon** [comment]
Closing stale PR.

**Pull request closed without merging**
